config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root "home#index"
  resources :about, only: :index
  resources :contact, only: :index
  resources :service, only: :index
  resources :blog, only: :index

  get 'apply_filters', to: 'home#apply_filters', as: :apply_filters

  get '/signup', to: 'users#new'
  get '/show', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/add_to_cart/:product_id', to: 'orders#add_to_cart', as: :add_to_cart
  get '/create_order', to: 'orders#convert_cart_to_order', as: :create_order
  get '/view_cart', to: 'orders#view_cart', as: :view_cart
  delete '/remove_product_from_cart/:order_item_id', to: 'orders#remove_product_from_cart', as: :remove_product_from_cart

  resources :users
  resources :account_activations, only: [:edit]

  get 'admin/view_orders', to: 'admin#view_orders', as: :view_orders
  delete 'admin/destroy_order/:id', to: 'admin#destroy_order', as: :destroy_order
  post 'admin/mark_order_as_handled/:id', to: 'admin#mark_order_as_handled', as: :mark_order_as_handled

  get 'admin/view_users', to: 'admin#view_users', as: :view_users
  get 'admin/view_profile/:id', to: 'admin#view_profile', as: :view_profile
  delete 'admin/destroy_user/:id', to: 'admin#destroy_user', as: :destroy_user

  get 'admin/view_products', to: 'admin#view_products', as: :view_products
  get 'admin/create_product', to: 'admin#create_product', as: :create_product
  post 'admin/create_product', to: 'admin#create_product'
  post 'admin/edit_product/:id', to: 'admin#edit_product', as: :edit_product
  patch 'admin/update_product/:id', to: 'admin#update_product', as: :update_product
  delete 'admin/destroy_product/:id', to: 'admin#destroy_product', as: :destroy_product

  namespace :api do
    resources :home, only: :index
    get '/signup', to: 'users#new'
    post '/login', to: 'authentication#login', as: :login
    post '/logout', to: 'authentication#logout', as: :logout

    resources :users

    post '/add_to_cart/:product_id', to: 'orders#add_to_cart', as: :add_to_cart
    post '/create_order', to: 'orders#convert_cart_to_order', as: :create_order
    get '/view_cart', to: 'orders#view_cart', as: :view_cart

    get 'apply_filters', to: 'home#apply_filters', as: :apply_filters

    get 'admin/view_profile/:id', to: 'admin#view_profile', as: :view_profile

    get 'admin/view_products', to: 'admin#view_products', as: :view_products
    get 'admin/view_orders', to: 'admin#view_orders', as: :view_orders
    post 'admin/mark_order_as_handled/:id', to: 'admin#mark_order_as_handled', as: :mark_order_as_handled
    get 'admin/view_users', to: 'admin#view_users', as: :view_users
    delete 'admin/destroy_user/:id', to: 'admin#destroy_user', as: :destroy_user

    post 'admin/edit_product/:id', to: 'admin#edit_product', as: :edit_product
    patch 'admin/update_product/:id', to: 'admin#update_product', as: :update_product
  end
end

app/views/admin/_form.html.erb
<%= form_with(model: @product, url: update_product_path(@product), local: true, method: :patch) do |f| %>
  <%= render 'shared/product_error_messages' %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label :description %>
  <%= f.text_area :description, class: 'form-control' %>

  <%= f.label :price %>
  <%= f.number_field :price, class: 'form-control' %>

  <%= f.label :vegetarian %>
  <%= f.check_box :vegetarian, class: 'form-check-input' %>

  <%= f.label :category_id, "form-control" %>
  <%= f.collection_select :category_id, Category.all, :id, :category_name, { prompt: "Select a category" }, class: 'form-select' %>

  <%= f.submit "Save changes", class: "btn btn-primary" %>
<% end %>

app/views/admin/_order.html.erb
<li>
  <strong>ID:</strong> <%= order.id %><br>
  <strong>User ID:</strong> <%= order.user_id %><br>
  <strong>User Name:</strong> <%= order.user.name %><br>
  <strong>Total:</strong> <%= order.total %><br>
  <strong>Is Cart:</strong> <%= order.isCart %><br>
  <strong>Status:</strong> <%= order.status == 'unhandled' ? content_tag(:span, order.status, class: 'text-danger') : order.status %><br>

  <% if order.unhandled? %>
    <%= button_to "Mark as Handled", mark_order_as_handled_path(order), method: :post %>
  <% end %>
  <%= button_to "Delete", destroy_order_path(order), method: :delete, data: { confirm: "Are you sure you want to delete this order?" } %>
  <br>
</li>

app/views/admin/_product.html.erb
<li>
  <strong>ID:</strong> <%= product.id %><br>
  <strong>Title:</strong> <%= product.title %><br>
  <strong>Description:</strong> <%= product.description %><br>
  <strong>Price:</strong> <%= "#{product.price} $" %><br>
  <strong>Vegetarian:</strong> <%= product.vegetarian %><br>
  <strong>Category:</strong> <%= product.category.category_name %><br>

  <%= button_to "Edit", edit_product_path(product) %>
  <%= button_to "Delete", destroy_product_path(product), method: :delete, data: { confirm: "Are you sure you want to delete this product?" } %>
  <br>
</li>

app/views/admin/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  |  <%= button_to "Delete User", destroy_user_path(user), method: :delete, data: { confirm: "Are you sure?" } %>
</li>

app/views/admin/destroy_order.html.erb
<h1>Admin#destroy_order</h1>
<p>Find me in app/views/admin/destroy_order.html.erb</p>

app/views/admin/edit_product.html.erb
<% provide(:title, "Edit product") %>
<% provide(:button_text, 'Save changes') %>
<h1>Update the product</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/mark_order_as_handled.html.erb
<h1>Admin#mark_order_as_handled</h1>
<p>Find me in app/views/admin/mark_order_as_handled.html.erb</p>

app/views/admin/view_orders.html.erb
<% provide(:title, 'All orders') %>
<h1>All orders</h1>

<%= will_paginate @orders %>

<ul class="orders">
  <%= render partial: 'admin/order', collection: @orders %>
</ul>

<%= will_paginate @orders %>

app/views/admin/view_products.html.erb
<% provide(:title, 'All products') %>
<h1>All products</h1>

<%= will_paginate @products %>

<ul class="products">
  <%= render partial: 'admin/product', collection: @products %>
</ul>

<%= will_paginate @products %>

app/views/admin/view_profile.html.erb
<% provide(:title, "Admin: #{@user.name}") %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= "Admin: #{@user.name}" %>
      </h1>
    </section>
  </aside>
</div>

app/views/admin/view_users.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate @users%>

<ul class="users">
  <%= render partial: 'admin/user', collection: @users %>
</ul>

<%= will_paginate @users%>