config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root "home#index"
  resources :about, only: :index
  resources :contact, only: :index
  resources :service, only: :index
  resources :blog, only: :index

  get 'apply_filters', to: 'home#apply_filters', as: :apply_filters

  get '/signup', to: 'users#new'
  get '/show', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/add_to_cart/:product_id', to: 'orders#add_to_cart', as: :add_to_cart
  get '/create_order', to: 'orders#convert_cart_to_order', as: :create_order
  get '/view_cart', to: 'orders#view_cart', as: :view_cart
  delete '/remove_product_from_cart/:order_item_id', to: 'orders#remove_product_from_cart', as: :remove_product_from_cart

  resources :users
  resources :account_activations, only: [:edit]

  get 'admin/view_orders', to: 'admin#view_orders', as: :view_orders
  delete 'admin/destroy_order/:id', to: 'admin#destroy_order', as: :destroy_order
  post 'admin/mark_order_as_handled/:id', to: 'admin#mark_order_as_handled', as: :mark_order_as_handled

  get 'admin/view_users', to: 'admin#view_users', as: :view_users
  get 'admin/view_profile/:id', to: 'admin#view_profile', as: :view_profile
  delete 'admin/destroy_user/:id', to: 'admin#destroy_user', as: :destroy_user

  get 'admin/view_products', to: 'admin#view_products', as: :view_products
  get 'admin/create_product', to: 'admin#create_product', as: :create_product
  post 'admin/create_product', to: 'admin#create_product'
  post 'admin/edit_product/:id', to: 'admin#edit_product', as: :edit_product
  patch 'admin/update_product/:id', to: 'admin#update_product', as: :update_product
  delete 'admin/destroy_product/:id', to: 'admin#destroy_product', as: :destroy_product

  namespace :api do
    resources :home, only: :index
    get '/signup', to: 'users#new'
    post '/login', to: 'authentication#login', as: :login
    post '/logout', to: 'authentication#logout', as: :logout

    resources :users

    post '/add_to_cart/:product_id', to: 'orders#add_to_cart', as: :add_to_cart
    post '/create_order', to: 'orders#convert_cart_to_order', as: :create_order
    get '/view_cart', to: 'orders#view_cart', as: :view_cart

    get 'apply_filters', to: 'home#apply_filters', as: :apply_filters

    get 'admin/view_profile/:id', to: 'admin#view_profile', as: :view_profile

    get 'admin/view_products', to: 'admin#view_products', as: :view_products
    get 'admin/view_orders', to: 'admin#view_orders', as: :view_orders
    post 'admin/mark_order_as_handled/:id', to: 'admin#mark_order_as_handled', as: :mark_order_as_handled
    get 'admin/view_users', to: 'admin#view_users', as: :view_users
    delete 'admin/destroy_user/:id', to: 'admin#destroy_user', as: :destroy_user

    post 'admin/edit_product/:id', to: 'admin#edit_product', as: :edit_product
    patch 'admin/update_product/:id', to: 'admin#update_product', as: :update_product
  end
end

app/controllers/api/home_controller.rb
require 'product_filter_service'

class Api::HomeController < Api::ApplicationController
  before_action :current_authorized_user, only: [:index]

  def index
    @products = Product.all
    @filter_params = {}

    @filter_params[:category] = params[:category]
    @filter_params[:vegetarian] = params[:vegetarian]
    @filter_params['price-sorting'] = params['price-sorting']
    @filter_params[:min_price] = params[:min_price]
    @filter_params[:max_price] = params[:max_price]

    render json: @products, each_serializer: ProductSerializer
  end

  def apply_filters
    product_filter_service = ProductFilterService.new(params)
    @products = product_filter_service.filter_products

    render json: @products, each_serializer: ProductSerializer
  end
end

app/controllers/home_controller.rb
require 'product_filter_service'

class HomeController < ApplicationController
  def index
    @products = Product.all
    @filter_params = {}

    @filter_params[:category] = params[:category]
    @filter_params[:vegetarian] = params[:vegetarian]
    @filter_params['price-sorting'] = params['price-sorting']
    @filter_params[:min_price] = params[:min_price]
    @filter_params[:max_price] = params[:max_price]
  end

  def apply_filters
    product_filter_service = ProductFilterService.new(params)
    @products = product_filter_service.filter_products
    render :index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag 'style', media: 'all', 'data-turbolinks-track': 'reload' %>
    <title>Food shop</title>
  </head>

  <!-- body -->
  <body>
    <!-- filters -->
    <div id="filter-div">
      <%= form_tag apply_filters_path, method: :get do %>
        <%= select_tag(:category, options_for_select([["All Categories", ""],["Pizza",1],["Pasta",2],["Salad",3],["Soup",4]], params[:category]), id: "category") %>
        <%= select_tag(:vegetarian, options_for_select([["Vegetarian: No", false], ["Vegetarian: Yes", true]], params[:vegetarian]), id: "vegetarian") %>
        <%= select_tag('price-sorting', options_for_select([["Ascending", "asc"], ["Descending", "desc"]], params['price-sorting']), id: "price-sorting") %>

        <!-- price range -->
        <div class="wrapper">
          <div class="price-input">
            <div class="field">
              <span>Min</span>
              <input type="number" class="input-min" name="min_price" value="<%= params[:min_price] || 10 %>">
            </div>
          </div>

          <div class="middle">
            <div class="slider">
              <div class="progress"></div>
            </div>
            <div class="range-input">
              <input type="range" class="range-min" name="min_price" min="0" max="50" value="<%= params[:min_price] || 10 %>" step="1">
              <input type="range" class="range-max" name="max_price" min="0" max="50" value="<%= params[:max_price] || 30 %>" step="1">
            </div>
          </div>

          <div class="price-input">
            <div class="field">
              <input type="number" class="input-max" name="max_price" value="<%= params[:max_price] || 30 %>">
              <span>Max</span>
            </div>
          </div>
        </div>
        <%= submit_tag "Apply Filters" %>
      <% end %>

      <% if logged_in? %>
        <%= link_to "View Cart", view_cart_path, class: "btn btn-primary create_order_button"%>
        <%= link_to "Create Order", create_order_path, method: :post, class: "btn btn-primary create_order_button" %>
      <% end %>
    </div>

    <!-- products display -->
    <div class="products">
      <% @products.each do |product| %>
        <div class="individual-product">
          <img src="<%= product.image.url %>" alt="<%= product.title %>">
          <h3 class="product-name"><%= product.title %></h3>
          <h4 class="product-category"><%= product.category.category_name %></h4>
          <h4 class="product-description"><%= product.description %></h4>
          <h4 class="product-price"><%= product.price %> $</h4>
          <% if logged_in? %>
            <% filtered_params = @filter_params&.compact || {} %>
            <%= link_to "Add to Cart", add_to_cart_path(product_id: product.id, **filtered_params), method: :post, class: "btn btn-primary add_to_cart_button" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </body>
</html>