config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  root "home#index"
  resources :about, only: :index
  resources :contact, only: :index
  resources :service, only: :index
  resources :blog, only: :index

  get 'apply_filters', to: 'home#apply_filters', as: :apply_filters

  get '/signup', to: 'users#new'
  get '/show', to: 'users#show'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  get '/add_to_cart/:product_id', to: 'orders#add_to_cart', as: :add_to_cart
  get '/create_order', to: 'orders#convert_cart_to_order', as: :create_order
  get '/view_cart', to: 'orders#view_cart', as: :view_cart
  delete '/remove_product_from_cart/:order_item_id', to: 'orders#remove_product_from_cart', as: :remove_product_from_cart

  resources :users
  resources :account_activations, only: [:edit]

  get 'admin/view_orders', to: 'admin#view_orders', as: :view_orders
  delete 'admin/destroy_order/:id', to: 'admin#destroy_order', as: :destroy_order
  post 'admin/mark_order_as_handled/:id', to: 'admin#mark_order_as_handled', as: :mark_order_as_handled

  get 'admin/view_users', to: 'admin#view_users', as: :view_users
  get 'admin/view_profile/:id', to: 'admin#view_profile', as: :view_profile
  delete 'admin/destroy_user/:id', to: 'admin#destroy_user', as: :destroy_user

  get 'admin/view_products', to: 'admin#view_products', as: :view_products
  get 'admin/create_product', to: 'admin#create_product', as: :create_product
  post 'admin/create_product', to: 'admin#create_product'
  post 'admin/edit_product/:id', to: 'admin#edit_product', as: :edit_product
  patch 'admin/update_product/:id', to: 'admin#update_product', as: :update_product
  delete 'admin/destroy_product/:id', to: 'admin#destroy_product', as: :destroy_product

  namespace :api do
    resources :home, only: :index
    get '/signup', to: 'users#new'
    post '/login', to: 'authentication#login', as: :login
    post '/logout', to: 'authentication#logout', as: :logout

    resources :users

    post '/add_to_cart/:product_id', to: 'orders#add_to_cart', as: :add_to_cart
    post '/create_order', to: 'orders#convert_cart_to_order', as: :create_order
    get '/view_cart', to: 'orders#view_cart', as: :view_cart

    get 'apply_filters', to: 'home#apply_filters', as: :apply_filters

    get 'admin/view_profile/:id', to: 'admin#view_profile', as: :view_profile

    get 'admin/view_products', to: 'admin#view_products', as: :view_products
    get 'admin/view_orders', to: 'admin#view_orders', as: :view_orders
    post 'admin/mark_order_as_handled/:id', to: 'admin#mark_order_as_handled', as: :mark_order_as_handled
    get 'admin/view_users', to: 'admin#view_users', as: :view_users
    delete 'admin/destroy_user/:id', to: 'admin#destroy_user', as: :destroy_user

    post 'admin/edit_product/:id', to: 'admin#edit_product', as: :edit_product
    patch 'admin/update_product/:id', to: 'admin#update_product', as: :update_product
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <br>
  <br>
  <br>
  <br>
  <div id="footer">
    <div id="footer-text">
      <p id="footer-text-p">© 2023 Fire delight. All rights reserved.</p>
    </div>
    <div id="footer-social">
      <a href="https://www.facebook.com/"><img src="https://www.facebook.com/images/fb_icon_325x325.png" alt="facebook" style="width:50px;height:50px;"></a>
      <a href="https://www.instagram.com/"><img src="https://upload.wikimedia.org/wikipedia/commons/9/95/Instagram_logo_2022.svg" alt="instagram" style="width:50px;height:50px;"></a>
      <a href="https://www.twitter.com/"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Logo_of_Twitter.svg/1200px-Logo_of_Twitter.svg.png" alt="twitter" style="width:50px;height:50px;"></a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="img-background"></div>  
  <h1 id="ord-txt">Ordering food</h1>
  <img id="logo" src="<%= image_path('logo.jpg') %>" alt="food">
  <h3 id="logo-name">Fire delight</h3>
  <hr>

  <!-- top menu -->
  <ul class="menu">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_index_path %></li>
    <li><%= link_to 'Service', service_index_path %></li>
    <li><%= link_to 'Blog', blog_index_path %></li>
    <li><%= link_to 'Contacts', contact_index_path %></li>
    <li><%= link_to "Sign up", signup_path %></li>
    <% if logged_in? %>
      <% if current_user.admin?%>
        <li><%= link_to "Users", view_users_path %></li>
        <li><%= link_to "Orders", view_orders_path %></li>
        <li><%= link_to "Products", view_products_path %></li>
      <% else %>
        <li><%= link_to "Users", users_path %></li>
      <% end %>
      <li class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Account <b class="caret"></b>
        </button>
        <ul class="dropdown-menu">
          <% if current_user.admin?%>
            <li><%= link_to "Profile", view_profile_path(current_user) %></li>
          <% else %>
            <li><%= link_to "Profile", current_user %></li>
          <% end %>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><%= link_to "Log in", login_path %></li>
    <% end %>
  </ul>
  <p id="description">
    We eat with our eyes first, but before we see our food, we picture it while reading the menu descriptions. They say one image is worth a thousand words, but don't underestimate the power of words.
  </p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Asg3</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>